### ISSUE TITLE
Debian (debian:12.1-slim) has libvips.so.42, not libvips / libvips.42.so

### ISSUE THREAD

**Issue by alexandergunnarson** [lopcode/vips-ffm#121]
First of all, amazing library!! 👏 About to use it in production with 1M users.

So, `VipsLibLookup` on Linux expects either libvips.so or libvips.42.so:

https://github.com/lopcode/vips-ffm/blob/704082f01ce2983eb04fe4639e01fb1075bd8fe0/core/src/main/java/app/photofox/vipsffm/VipsLibLookup.java#L37

However, Debian (specifically debian:12.1-slim) has libvips.so.42. For now, I'm hard-linking the files, but it would be beneficial to address the root cause here.

Thank you!

**Comment by lopcode** [comment]
Thanks for raising an issue and letting me know you're shipping the library to a bunch of users 🎉 

I did some investigating and I confirmed this seems to work on `debian:12.1-slim` out of the box. 

Specifically, if you start a bash shell inside that container, and run `ldconfig -p | grep vips`:
```
root@1af87c70101c:/# ldconfig -p | grep vips
	libvips.so.42 (libc6,AArch64) => /lib/aarch64-linux-gnu/libvips.so.42
	libvips.so (libc6,AArch64) => /lib/aarch64-linux-gnu/libvips.so
	libvips-cpp.so.42 (libc6,AArch64) => /lib/aarch64-linux-gnu/libvips-cpp.so.42
	libvips-cpp.so (libc6,AArch64) => /lib/aarch64-linux-gnu/libvips-cpp.so
```

it seems debian **do** symlink to `libvips.so`, which means by default it'll get picked up by the [first search path](https://github.com/lopcode/vips-ffm/blob/704082f01ce2983eb04fe4639e01fb1075bd8fe0/core/src/main/java/app/photofox/vipsffm/VipsLibLookup.java#L36).

Library search path stuff is a real pain, so I started a Docker test suite, which can also serve as examples for folks to look at.

Could you take a look at the PR above (#122) and see what you think @alexandergunnarson - as far as I can tell, you shouldn't have to hardcode a path?

**Comment by alexandergunnarson** [comment]
Also — I'm working through this — but a crash we get in CI after installing `libvips-tools` and trying to load  vips-ffm is 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ef958c1924b, pid=13615, tid=13709
#
# JRE version: OpenJDK Runtime Environment (24.0) (build 24)
# Java VM: OpenJDK 64-Bit Server VM (24, mixed mode, tiered, compressed class ptrs, z gc, linux-amd64)
# Problematic frame:
# C  [libcrypto.so.3+0x29f24b]  SHA256_Update+0x15b
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to ...)
#
# An error report file with more information is saved as:
# .../hs_err_pid13615.log
[228.095s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

I'm trying libvips-dev now to see if it fixes the issue, but perhaps it's something else.

**Comment by alexandergunnarson** [comment]
Likely it's a library incompatibility, possibly introduced by `libvips-dev` as opposed to `libvips-tools`, but in any case outside the scope of this repo. Feel free to ignore that crash report!

**Comment by lopcode** [comment]
That stacktrace is definitely weird - I think you're right about the minimal image needing more dependencies installed. I've signposted `libvips-dev` in the README seeing as that's what's tested against.

It sounds like you've figured things out with regard to the original issue, but let me know how you get on, and if you get stuck.

**Comment by alexandergunnarson** [comment]
libvips-dev ended up working once I replaced an old Java SSL library with a different, much more recent one. Strange that the old Java SSL library stopped working - it’s been fine for over a decade. Anyway, thank you for your help!

**Comment by lopcode** [comment]
Just FYI - I merged a change that allows the smaller runtime package to be installed instead - `libvips42`. `libvips-dev` includes all the development header stuff, which isn't strictly necessary.

You can use either `libvips42` or `libvips-dev` as of version `v1.9.6`.
