### ISSUE TITLE
VipsIccTransform wrong arguments

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#60]
Running on windows, v. 0.5.0:

```
(process:19900): GLib-GObject-CRITICAL **: 16:54:52.044: g_object_set_is_valid_property: object class 'VipsIccTransform' has no property named 'outputProfile'
```

Issue seems to be this line in VImage:
        VipsOption.String outputProfileOption = VipsOption.String("outputProfile", outputProfile);

https://www.libvips.org/API/current/libvips-colour.html#vips-icc-transform

The version 8.15.3 doesn't have that property on that method.

**Comment by lopcode** [comment]
Pretty sure this is because I'm using the "Java style" name for the option instead of the Vips style - I'll fix it today and do another release

**Comment by lopcode** [comment]
This is fixed in `0.5.1`, just published to Maven Central (might take a few minutes for it to become available) 🤞

**Comment by JohannesBeranek** [comment]
This part works now.

**Comment by JohannesBeranek** [comment]
This part works now.
