### ISSUE TITLE
Question: Vips.init & threads

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#73]
Going by the code of Vips.init() and Vips.shutdown(), I would assume to only call both once per application and not once per thread. The library would then be usable from all threads, without any kind of synchronization needed, as long as someone doesn't share VImage objects or the like across threads.

Or do I need to always call Vips.init() and Vips.shutdown() in every thread where vips-ffm is used? 

Thanks!

**Comment by lopcode** [comment]
vips-ffm doesn't do anything special with threading and the rules will generally be whatever works for libvips - I believe you're right and that initialising once on any thread will be enough, and shutting down once on any thread is also fine

I think however that an "Arena.ofConfined" might have threading requirements - so any "Vips.run" call likely needs to have all users of the provided arena do so from the same thread

**Comment by JohannesBeranek** [comment]
Thanks!

**Comment by JohannesBeranek** [comment]
Thanks!
