### ISSUE TITLE
Saving image to format determined by file extension

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#81]
vips-ffm provides VImage::writeToTarget which, as far as I understood from libvips documentation itself, should allow to save an image without knowing what the target format will be, and have the library automatically determine it based on the format option (which should actually be the filename suffix, so include the leading ".", according to my testing).

How would one get a byte array out of a VTarget?

vTarget.getUnsafeStructAddress().asByteBuffer()

does not seem to give a byte buffer of the image or it's missing a NUL terminator or has some other issue.

**Comment by lopcode** [comment]
Had a look at how other bindings do this - they seem to just expose the underlying `blob` for access, with a warning about only using it with memory-backed targets, so I've done the same and added `VTarget.getBlob` to get the `VBlob` in `0.5.12` 🙂

**Comment by JohannesBeranek** [comment]
Seems to work so far. Let me do a little bit more testing, then I'll be happy to close this if that's alright with you?

**Comment by lopcode** [comment]
Yep sounds good to me 👍

**Comment by lopcode** [comment]
Checking in to see if I can close this issue now, @JohannesBeranek?

**Comment by JohannesBeranek** [comment]
Sorry for the late response, but looks good now, thanks!
